/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ev-car.glb -o components/landing/hero3d/models/EvCar.tsx -t -k -s 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['NormalCar1_Cube012-Mesh']: THREE.Mesh
    ['NormalCar1_Cube012-Mesh_1']: THREE.Mesh
    ['NormalCar1_Cube012-Mesh_2']: THREE.Mesh
    ['NormalCar1_Cube012-Mesh_3']: THREE.Mesh
    ['NormalCar1_Cube012-Mesh_4']: THREE.Mesh
    ['NormalCar1_Cube012-Mesh_5']: THREE.Mesh
    ['NormalCar1_BackWheels_Cube011-Mesh']: THREE.Mesh
    ['NormalCar1_BackWheels_Cube011-Mesh_1']: THREE.Mesh
    ['NormalCar1_FrontLeftWheel_Cube007-Mesh']: THREE.Mesh
    ['NormalCar1_FrontLeftWheel_Cube007-Mesh_1']: THREE.Mesh
    ['NormalCar1_FrontRightWheel_Cube008-Mesh']: THREE.Mesh
    ['NormalCar1_FrontRightWheel_Cube008-Mesh_1']: THREE.Mesh
  }
  materials: {
    Blue: THREE.MeshStandardMaterial
    Windows: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Headlights: THREE.MeshStandardMaterial
    TailLights: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/ev-car.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="NormalCar1_Cube012-Mesh" castShadow receiveShadow geometry={nodes['NormalCar1_Cube012-Mesh'].geometry} material={materials.Blue} />
      <mesh name="NormalCar1_Cube012-Mesh_1" castShadow receiveShadow geometry={nodes['NormalCar1_Cube012-Mesh_1'].geometry} material={materials.Windows} />
      <mesh name="NormalCar1_Cube012-Mesh_2" castShadow receiveShadow geometry={nodes['NormalCar1_Cube012-Mesh_2'].geometry} material={materials.Black} />
      <mesh name="NormalCar1_Cube012-Mesh_3" castShadow receiveShadow geometry={nodes['NormalCar1_Cube012-Mesh_3'].geometry} material={materials.Grey} />
      <mesh name="NormalCar1_Cube012-Mesh_4" castShadow receiveShadow geometry={nodes['NormalCar1_Cube012-Mesh_4'].geometry} material={materials.Headlights} />
      <mesh name="NormalCar1_Cube012-Mesh_5" castShadow receiveShadow geometry={nodes['NormalCar1_Cube012-Mesh_5'].geometry} material={materials.TailLights} />
      <mesh name="NormalCar1_BackWheels_Cube011-Mesh" castShadow receiveShadow geometry={nodes['NormalCar1_BackWheels_Cube011-Mesh'].geometry} material={materials.Black} />
      <mesh name="NormalCar1_BackWheels_Cube011-Mesh_1" castShadow receiveShadow geometry={nodes['NormalCar1_BackWheels_Cube011-Mesh_1'].geometry} material={materials.Grey} />
      <mesh name="NormalCar1_FrontLeftWheel_Cube007-Mesh" castShadow receiveShadow geometry={nodes['NormalCar1_FrontLeftWheel_Cube007-Mesh'].geometry} material={materials.Grey} />
      <mesh name="NormalCar1_FrontLeftWheel_Cube007-Mesh_1" castShadow receiveShadow geometry={nodes['NormalCar1_FrontLeftWheel_Cube007-Mesh_1'].geometry} material={materials.Black} />
      <mesh name="NormalCar1_FrontRightWheel_Cube008-Mesh" castShadow receiveShadow geometry={nodes['NormalCar1_FrontRightWheel_Cube008-Mesh'].geometry} material={materials.Grey} />
      <mesh name="NormalCar1_FrontRightWheel_Cube008-Mesh_1" castShadow receiveShadow geometry={nodes['NormalCar1_FrontRightWheel_Cube008-Mesh_1'].geometry} material={materials.Black} />
    </group>
  )
}

useGLTF.preload('/models/ev-car.glb')
