/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ev-charger.glb -o components/landing/hero3d/models/EvCharger.tsx -t -k -s 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelUrl } from '@/lib/content'

const MODEL_URL = getModelUrl('evCharger')

type GLTFResult = GLTF & {
  nodes: {
    mesh1848869498: THREE.Mesh
    mesh1848869498_1: THREE.Mesh
    mesh1848869498_2: THREE.Mesh
    mesh1848869498_3: THREE.Mesh
    mesh1848869498_4: THREE.Mesh
    mesh1848869498_5: THREE.Mesh
    mesh1848869498_6: THREE.Mesh
    mesh1848869498_7: THREE.Mesh
    mesh1848869498_8: THREE.Mesh
    mesh1848869498_9: THREE.Mesh
    mesh1848869498_10: THREE.Mesh
    mesh1848869498_11: THREE.Mesh
    mesh1848869498_12: THREE.Mesh
    mesh1848869498_13: THREE.Mesh
    mesh1848869498_14: THREE.Mesh
    mesh1848869498_15: THREE.Mesh
    mesh1848869498_16: THREE.Mesh
    mesh1848869498_17: THREE.Mesh
    mesh1848869498_18: THREE.Mesh
    mesh1848869498_19: THREE.Mesh
    mesh1848869498_20: THREE.Mesh
    mesh1848869498_21: THREE.Mesh
  }
  materials: {
    mat8: THREE.MeshStandardMaterial
    mat17: THREE.MeshStandardMaterial
    mat14: THREE.MeshStandardMaterial
    mat13: THREE.MeshStandardMaterial
    mat25: THREE.MeshStandardMaterial
    mat15: THREE.MeshStandardMaterial
    mat7: THREE.MeshStandardMaterial
    mat23: THREE.MeshStandardMaterial
    mat6: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat9: THREE.MeshStandardMaterial
    mat10: THREE.MeshStandardMaterial
    mat21: THREE.MeshStandardMaterial
    mat5: THREE.MeshStandardMaterial
    mat24: THREE.MeshStandardMaterial
    mat11: THREE.MeshStandardMaterial
    mat0: THREE.MeshStandardMaterial
    mat3: THREE.MeshStandardMaterial
    mat4: THREE.MeshStandardMaterial
    mat12: THREE.MeshStandardMaterial
    mat22: THREE.MeshStandardMaterial
    mat19: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_URL) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="mesh1848869498" castShadow receiveShadow geometry={nodes.mesh1848869498.geometry} material={materials.mat8} />
      <mesh name="mesh1848869498_1" castShadow receiveShadow geometry={nodes.mesh1848869498_1.geometry} material={materials.mat17} />
      <mesh name="mesh1848869498_2" castShadow receiveShadow geometry={nodes.mesh1848869498_2.geometry} material={materials.mat14} />
      <mesh name="mesh1848869498_3" castShadow receiveShadow geometry={nodes.mesh1848869498_3.geometry} material={materials.mat13} />
      <mesh name="mesh1848869498_4" castShadow receiveShadow geometry={nodes.mesh1848869498_4.geometry} material={materials.mat25} />
      <mesh name="mesh1848869498_5" castShadow receiveShadow geometry={nodes.mesh1848869498_5.geometry} material={materials.mat15} />
      <mesh name="mesh1848869498_6" castShadow receiveShadow geometry={nodes.mesh1848869498_6.geometry} material={materials.mat7} />
      <mesh name="mesh1848869498_7" castShadow receiveShadow geometry={nodes.mesh1848869498_7.geometry} material={materials.mat23} />
      <mesh name="mesh1848869498_8" castShadow receiveShadow geometry={nodes.mesh1848869498_8.geometry} material={materials.mat6} />
      <mesh name="mesh1848869498_9" castShadow receiveShadow geometry={nodes.mesh1848869498_9.geometry} material={materials.mat16} />
      <mesh name="mesh1848869498_10" castShadow receiveShadow geometry={nodes.mesh1848869498_10.geometry} material={materials.mat9} />
      <mesh name="mesh1848869498_11" castShadow receiveShadow geometry={nodes.mesh1848869498_11.geometry} material={materials.mat10} />
      <mesh name="mesh1848869498_12" castShadow receiveShadow geometry={nodes.mesh1848869498_12.geometry} material={materials.mat21} />
      <mesh name="mesh1848869498_13" castShadow receiveShadow geometry={nodes.mesh1848869498_13.geometry} material={materials.mat5} />
      <mesh name="mesh1848869498_14" castShadow receiveShadow geometry={nodes.mesh1848869498_14.geometry} material={materials.mat24} />
      <mesh name="mesh1848869498_15" castShadow receiveShadow geometry={nodes.mesh1848869498_15.geometry} material={materials.mat11} />
      <mesh name="mesh1848869498_16" castShadow receiveShadow geometry={nodes.mesh1848869498_16.geometry} material={materials.mat0} />
      <mesh name="mesh1848869498_17" castShadow receiveShadow geometry={nodes.mesh1848869498_17.geometry} material={materials.mat3} />
      <mesh name="mesh1848869498_18" castShadow receiveShadow geometry={nodes.mesh1848869498_18.geometry} material={materials.mat4} />
      <mesh name="mesh1848869498_19" castShadow receiveShadow geometry={nodes.mesh1848869498_19.geometry} material={materials.mat12} />
      <mesh name="mesh1848869498_20" castShadow receiveShadow geometry={nodes.mesh1848869498_20.geometry} material={materials.mat22} />
      <mesh name="mesh1848869498_21" castShadow receiveShadow geometry={nodes.mesh1848869498_21.geometry} material={materials.mat19} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
