/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/server-rack.glb -o components/landing/hero3d/models/ServerRack.tsx -t -k -s 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { getModelUrl } from '@/lib/content'

const MODEL_URL = getModelUrl('serverRack')

type GLTFResult = GLTF & {
  nodes: {
    console: THREE.Mesh
    console_base_right: THREE.Mesh
    console_left: THREE.Mesh
    misc1: THREE.Mesh
    ['2u_nas1']: THREE.Mesh
    misc2: THREE.Mesh
    ups: THREE.Mesh
    ['1u_server9']: THREE.Mesh
    ['1u_server8']: THREE.Mesh
    ['1u_server7']: THREE.Mesh
    ['1u_server6']: THREE.Mesh
    ['1u_server5']: THREE.Mesh
    ['1u_server4']: THREE.Mesh
    ['1u_server3']: THREE.Mesh
    ['1u_server2']: THREE.Mesh
    ['1u_server1']: THREE.Mesh
    rack: THREE.Mesh
  }
  materials: {
    console_auv: THREE.MeshStandardMaterial
    Cube1_auv: THREE.MeshStandardMaterial
    Cube12_auv: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_URL) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="console" castShadow receiveShadow geometry={nodes.console.geometry} material={materials.console_auv} />
      <mesh name="console_base_right" castShadow receiveShadow geometry={nodes.console_base_right.geometry} material={materials.Cube1_auv} />
      <mesh name="console_left" castShadow receiveShadow geometry={nodes.console_left.geometry} material={materials.Cube1_auv} />
      <mesh name="misc1" castShadow receiveShadow geometry={nodes.misc1.geometry} material={materials.Cube12_auv} />
      <mesh name="2u_nas1" castShadow receiveShadow geometry={nodes['2u_nas1'].geometry} material={materials.Cube12_auv} />
      <mesh name="misc2" castShadow receiveShadow geometry={nodes.misc2.geometry} material={materials.Cube12_auv} />
      <mesh name="ups" castShadow receiveShadow geometry={nodes.ups.geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server9" castShadow receiveShadow geometry={nodes['1u_server9'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server8" castShadow receiveShadow geometry={nodes['1u_server8'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server7" castShadow receiveShadow geometry={nodes['1u_server7'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server6" castShadow receiveShadow geometry={nodes['1u_server6'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server5" castShadow receiveShadow geometry={nodes['1u_server5'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server4" castShadow receiveShadow geometry={nodes['1u_server4'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server3" castShadow receiveShadow geometry={nodes['1u_server3'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server2" castShadow receiveShadow geometry={nodes['1u_server2'].geometry} material={materials.Cube12_auv} />
      <mesh name="1u_server1" castShadow receiveShadow geometry={nodes['1u_server1'].geometry} material={materials.Cube12_auv} />
      <mesh name="rack" castShadow receiveShadow geometry={nodes.rack.geometry} material={materials.Cube1_auv} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
