import type { EvPreset } from "@/types";

/** Built-in vehicle presets — mirrors backend/app/virtual_ev/presets.py */
export const EV_PRESETS: EvPreset[] = [
  {
    id: "tesla-model-3-lr",
    name: "Tesla Model 3 Long Range",
    vendor: "Tesla",
    model: "Model 3 LR",
    evType: "BEV",
    batteryCapacityKwh: 82,
    maxAcChargePowerKw: 11.5,
    maxDcChargePowerKw: 250,
  },
  {
    id: "nissan-leaf-plus",
    name: "Nissan Leaf e+",
    vendor: "Nissan",
    model: "Leaf e+",
    evType: "BEV",
    batteryCapacityKwh: 62,
    maxAcChargePowerKw: 6.6,
    maxDcChargePowerKw: 100,
  },
  {
    id: "bmw-i4",
    name: "BMW i4 eDrive40",
    vendor: "BMW",
    model: "i4 eDrive40",
    evType: "BEV",
    batteryCapacityKwh: 83.9,
    maxAcChargePowerKw: 11,
    maxDcChargePowerKw: 205,
  },
  {
    id: "hyundai-ioniq5",
    name: "Hyundai IONIQ 5",
    vendor: "Hyundai",
    model: "IONIQ 5",
    evType: "BEV",
    batteryCapacityKwh: 77.4,
    maxAcChargePowerKw: 11,
    maxDcChargePowerKw: 233,
  },
  {
    id: "chevy-bolt",
    name: "Chevrolet Bolt EV",
    vendor: "Chevrolet",
    model: "Bolt EV",
    evType: "BEV",
    batteryCapacityKwh: 65,
    maxAcChargePowerKw: 7.7,
    maxDcChargePowerKw: 55,
  },
  {
    id: "vw-id4",
    name: "Volkswagen ID.4",
    vendor: "Volkswagen",
    model: "ID.4 Pro",
    evType: "BEV",
    batteryCapacityKwh: 82,
    maxAcChargePowerKw: 11,
    maxDcChargePowerKw: 135,
  },
  {
    id: "toyota-prius-prime",
    name: "Toyota Prius Prime",
    vendor: "Toyota",
    model: "Prius Prime",
    evType: "PHEV",
    batteryCapacityKwh: 13.6,
    maxAcChargePowerKw: 3.3,
    maxDcChargePowerKw: 0,
  },
  {
    id: "generic-bev",
    name: "Generic BEV",
    vendor: "Generic",
    model: "Standard BEV",
    evType: "BEV",
    batteryCapacityKwh: 75,
    maxAcChargePowerKw: 11,
    maxDcChargePowerKw: 150,
  },
];
